name: push
on: 
  push:
    branches:
      - master
      - main
    tags:        
      - v*

jobs:
  call-workflow:
    uses: raf-backstage-demo/shared-workflows/.github/workflows/dotnet-ci-cd.yaml@main
    with:
      app: ${{values.application.split(":")[1]}}