description: ${{values.description}}
os: ${{values.os}}
disk: ${{values.disk}}
cores: ${{values.cores}}
memory: ${{values.memory}}
initpwd: ${{values.initpwd}}
application_id: ${{values.application_id}}
# optional
workload: ${{values.workload}}
flavor: ${{values.flavor}}
environments: ${{values.environments}}
