# dummy
{%- for environment in values.environments %}
${{environment}}:
  description: ${{values.description}}
  os: ${{values.os}}
  disk: ${{values.disk}}
  cores: ${{values.cores}}
  memory: ${{values.memory}}
  initpwd: ${{values.initpwd}}
  application_id: ${{values.application_id}}
  running: ${{values.running}}
  environment: ${{environment}}
  # optional
  workload: ${{values.workload}}
  flavor: ${{values.flavor}}
{%- endfor %}
