{%- for environment in values.environments %}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{values.application_id}}-${{environment}}
  namespace: suxess-it-admin
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/phac008/${{values.application_id}}-gitops.git
    targetRevision: HEAD
    path: helm/chart
    helm:
      values: |
        description: ${{values.description}}
        os: ${{values.os}}
        disk: ${{values.disk}}
        cores: ${{values.cores}}
        memory: ${{values.memory}}
        initpwd: ${{values.initpwd}}
        application_id: ${{values.application_id}}
        running: ${{values.running}}
        environment: ${{environment}}
        # optional
        workload: ${{values.workload}}
        flavor: ${{values.flavor}}

  destination:
    server: https://kubernetes.default.svc
    namespace: suxess-it-${{environment}}
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=false      
    retry:
      limit: 0 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
{%- endfor %}

