apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "${{values.application_id}}"
  description: "${{values.application_id}}"
  tags:
    - sx
    - template
    - metalstack
  links:
    - url: https://grafana-metalstack.platform-engineer.cloud/
      title: Grafana SRE Metrics
      icon: web
  annotations:
    github.com/project-slug: ${{values.repoUrlowner}}/${{values.application_id}}
    backstage.io/kubernetes-id: app.kubernetes.io/instance=${{values.application_id}}
    kubecost.com/deployment-name: ${{values.application_id}}
    argocd/app-name: ${{values.application_id}}-${{values.environments}}
    backstage.io/kubernetes-namespace: ${{values.environments}}-demo-kubevirt
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> '4GoldenSignals')"
    grafana/overview-dashboard: "https://grafana-metalstack.platform-engineer.cloud/d/a87fb0d919ec0ea5f6543124e16c42a5/kubernetes-compute-resources-namespace-workloads?orgId=1&refresh=10s&var-datasource=default&var-cluster=&var-namespace=${{values.environments}}-demo-app&var-type=All"
spec:
  type: service
  lifecycle: experimental
  owner: "guests"
  system: vm:${{values.application_id}}
  dependsOn:
    - resource:argocd
